require("mb.options")
require("mb.plugins")
require("mb.keymaps")
require("mb.lsp")
require("mb.cmp")

require("mb.colorscheme")
require("mb.treesitter")
require("mb.whichkey")
require("mb.project")
require("mb.telescope")
require("mb.autopairs")
require("mb.autocommands")
require("mb.toggleterm")
require("mb.lualine")
require("mb.bufferline")
require("mb.alpha")
require("mb.comment")
require("mb.impatient")
require("mb.nvim-tree")
-- require("mb.copilot")
